### PR TITLE
Remove Duplicate Ores

### PR DESCRIPTION
**Pull request by dixonwille**
Really need a way to have minecraftinstance.json not checked in... It is changed everytime you load the game...

### CODE REVIEW

**Comment by tylersuggs** [comment]
Can’t build the instance without it.

**Comment by tylersuggs** [comment]
I don’t see any config change here?

**Comment by dixonwille** [comment]
Well crap... And yes you can. What we want is to be able to create a zip, not duplicate twitch launcher. I think I have a way to duplicate the zip stuff without having to check-in the Minecraft instance json file.

**Comment by tylersuggs** [comment]
Need to be able to build the twitch instance from source files for testing.

**Comment by tylersuggs** [comment]
There’s more work I have planned to separate client-only and server-only files and to include them in their respective builds. The instance manifest will help with that.

**Comment by dixonwille** [comment]
I will have a smaller file that isn't modified on every launch. Only when mods are installed. What information do you need specificly in the file?

**Comment by tylersuggs** [comment]
Wait... is your repo the instance folder that twitch uses?

**Comment by dixonwille** [comment]
Have you looked at the contents of the zip. It doesn't contain Minecraft instance json. So it is generated. So you don't need it to create zip and test that way.

**Review by tylersuggs — APPROVED** [review]

**Pull request merged**
